usr/bin/phosh-mobile-settings
usr/lib/*/phosh-mobile-settings/plugins/libms-plugin-librem5.so
usr/share/applications/mobi.phosh.MobileSettings.desktop
usr/share/icons/hicolor/scalable/apps/mobi.phosh.MobileSettings.svg
usr/share/icons/hicolor/symbolic/apps/mobi.phosh.MobileSettings-symbolic.svg
usr/share/locale/*/*/phosh-mobile-settings.mo
usr/share/metainfo/mobi.phosh.MobileSettings.metainfo.xml
